num = -1
soma = 0
cont = 0
while num != 999:
    num = int(input('Digite um número [999 para parar]: '))
    if num != 999:
        soma += num
        cont += 1
print('\nQuantidade de números: {}\nSoma entre eles = {}'.format(cont, soma))
